<a href="https://colab.research.google.com/github/RudreshKumarP/Python-ExcelR/blob/main/Basic_Programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Write Python Programs to use various operators in Python**

**Arithmetic**

In [ ]:
x= 10
y= 8

In [ ]:
print('x + y =',x+y)

x + y = 18


In [ ]:
print('x - y =',x-y)

x - y = 2


In [ ]:
print('x * y =',x*y)

x * y = 80


In [ ]:
print('x / y =',x/y)

x / y = 1.25


In [ ]:
print('x // y =',x//y)

x // y = 1


In [ ]:
print('x ** y=',x**y)

x ** y= 100000000


**Assignment Operators**

In [ ]:
a = 5
b = 6

# a = a + b
a += b

In [ ]:
print(a)

11


In [ ]:
a = 3
b = 5

# a = a - b
a -= b

In [ ]:
print(a)

-2


In [ ]:
a = 4
b = 7

# a = a * b
a *= b

In [ ]:
print(a)

28


In [ ]:
a = 2
b = 6

# a = a / b
a /= b

In [ ]:
print(a)

0.3333333333333333


In [ ]:
a = 6
b = 8

# a = a % b
a %= b

In [ ]:
print(a)

6


In [ ]:
a = 4
b = 9

# a = a // b
a //= b

In [ ]:
print(a)

0


**Relational operators**

In [ ]:
x = 12
y = 15

In [ ]:
print('x > y is',x>y)

x > y is False


In [ ]:
print('x < y is',x<y)

x < y is True


In [ ]:
print('x == y is',x==y)

x == y is False


In [ ]:
print('x != y is',x!=y)

x != y is True


In [ ]:
print('x >= y is',x>=y)

x >= y is False


In [ ]:
print('x <= y is',x<=y)

x <= y is True


**Logical operators**

In [ ]:
x = True
y = False

In [ ]:
print('x and y is', x and y)

x and y is False


In [ ]:
print('x or y is', x or y)

x or y is True


In [ ]:
print('not x is', not x)

not x is False


**Identity operators**

In [ ]:
x1 = 9
y1 = 9
x2 = 'Hello'
y2 = 'Hello'
x3 =[1,2,3]
y3 =[1,2,3]

In [ ]:
print(x1 is y1)

True


In [ ]:
print(x2 is y2)

True


In [ ]:
print(x3 is y3)

False


**Membership operators**

In [ ]:
x = 'Hello world'
y = {1:'a',2:'b'}

In [ ]:
print('Hello' in  x)

True


In [ ]:
print('hello' in x)

False


In [ ]:
print(1 in y)

True


In [ ]:
print('a' in y)

False


**2. Create list of elements and slice and dice it**

In [2]:
x= ['a', 'b', 'c', 'd', 'e']

In [3]:
x[1:4]

['b', 'c', 'd']

In [4]:
x[ :3]

['a', 'b', 'c']

In [5]:
x[2: ]

['c', 'd', 'e']

In [6]:
x[ : ]

['a', 'b', 'c', 'd', 'e']

**3. Using while loop accept numbers until sum of numbers is less than 100**

In [24]:
Sum = 0
i = 1
while Sum <= 90:
  Sum = Sum + i
  i = i + 1

print(" ", Sum)

  91


In [25]:
Sum = 0
i = 1
while  i <= 13:
  Sum = Sum + i
  i = i + 1

print(" ", Sum)

  91


**4. Write a python program Read & write Excel files**

In [37]:
import pandas as pd

In [38]:
path = "https://github.com/RudreshKumarP/Python-ExcelR/raw/main/crime_data.csv"
crime_data = pd.read_csv(path)
crime_data

Unnamed: 0  Murder  Assault  UrbanPop  Rape
0          Alabama    13.2      236        58  21.2
1           Alaska    10.0      263        48  44.5
2          Arizona     8.1      294        80  31.0
3         Arkansas     8.8      190        50  19.5
4       California     9.0      276        91  40.6
5         Colorado     7.9      204        78  38.7
6      Connecticut     3.3      110        77  11.1
7         Delaware     5.9      238        72  15.8
8          Florida    15.4      335        80  31.9
9          Georgia    17.4      211        60  25.8
10          Hawaii     5.3       46        83  20.2
11           Idaho     2.6      120        54  14.2
12        Illinois    10.4      249        83  24.0
13         Indiana     7.2      113        65  21.0
14            Iowa     2.2       56        57  11.3
15          Kansas     6.0      115        66  18.0
16        Kentucky     9.7      109        52  16.3
17       Louisiana    15.4      249        66  22.2
18           Maine     2.1       83        51   7.8
19        Maryland    11.3      300        67  27.8
20   Massachusetts     4.4      149        85  16.3
21        Michigan    12.1      255        74  35.1
22       Minnesota     2.7       72        66  14.9
23     Mississippi    16.1      259        44  17.1
24        Missouri     9.0      178        70  28.2
25         Montana     6.0      109        53  16.4
26        Nebraska     4.3      102        62  16.5
27          Nevada    12.2      252        81  46.0
28   New Hampshire     2.1       57        56   9.5
29      New Jersey     7.4      159        89  18.8
30      New Mexico    11.4      285        70  32.1
31        New York    11.1      254        86  26.1
32  North Carolina    13.0      337        45  16.1
33    North Dakota     0.8       45        44   7.3
34            Ohio     7.3      120        75  21.4
35        Oklahoma     6.6      151        68  20.0
36          Oregon     4.9      159        67  29.3
37    Pennsylvania     6.3      106        72  14.9
38    Rhode Island     3.4      174        87   8.3
39  South Carolina    14.4      279        48  22.5
40    South Dakota     3.8       86        45  12.8
41       Tennessee    13.2      188        59  26.9
42           Texas    12.7      201        80  25.5
43            Utah     3.2      120        80  22.9
44         Vermont     2.2       48        32  11.2
45        Virginia     8.5      156        63  20.7
46      Washington     4.0      145        73  26.2
47   West Virginia     5.7       81        39   9.3
48       Wisconsin     2.6       53        66  10.8
49         Wyoming     6.8      161        60  15.6

**5. Create a 3x3 matrix with values ranging from 2 to 10 using numpy**

In [43]:
import numpy as np

In [45]:
x=np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


**6. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array**

In [51]:
import numpy as np

List=[15.35, 60, 25, 23.85]
x=np.array(List)
print(x)

[15.35 60.   25.   23.85]


**7. "Write a Python program to create a null vector of size 10 and update sixth value to 11**

In [54]:
import numpy as np

vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [55]:
vector[6] = 11
print(vector)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
